#! /usr/bin/env python3


import argparse
import pyarrow.parquet as pq


parser = argparse.ArgumentParser(description='Process a filename.')
parser.add_argument('filename', type=str, help='The filename to process')
args = parser.parse_args()

tab = pq.read_table(args.filename)


print(tab)
